### ISSUE TITLE
Error: "Video has reversed metadata."

### ISSUE THREAD

**Issue by miahoffmannd** [freemocap/skelly_synchronize#42]
I have multiple recorded videos that I am synchronizing; I have previously had videos recorded with the same set up work. When running videos from today I am getting the following error message:

[2024-10-16 14:06:17.0037] [    INFO] [root] [trim_single_video_deffcode():26] [PID:40396 TID:33276] Video has reversed metadata, changing FFmpeg transpose argument
Traceback (most recent call last):
  File "C:\Users\miaea\anaconda3\envs\freemocap-env\Lib\site-packages\skelly_synchronize\gui\skelly_synchronize_gui.py", line 49, in <lambda>
    lambda: synchronize_videos_from_audio(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miaea\anaconda3\envs\freemocap-env\Lib\site-packages\skelly_synchronize\skelly_synchronize.py", line 123, in synchronize_videos_from_audio
    trim_videos(
  File "C:\Users\miaea\anaconda3\envs\freemocap-env\Lib\site-packages\skelly_synchronize\core_processes\video_functions\video_utilities.py", line 96, in trim_videos
    trim_single_video_deffcode(
  File "C:\Users\miaea\anaconda3\envs\freemocap-env\Lib\site-packages\skelly_synchronize\core_processes\video_functions\deffcode_functions.py", line 29, in trim_single_video_deffcode
    "-vf": tranposition_dictionary[
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: -180.0

**Comment by philipqueen** [comment]
Sorry for the delay in responding to this. I've pushes a patch to PyPI, which you can download with `pip install skelly_synchronize --upgrade` or `pip install skelly_synchronize==v2024.10.1034`
